# Generated by Django 5.2.4 on 2025-08-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficina', '0002_delete_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.oficina')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
